### PR TITLE
Update shortcodes

### PR DESCRIPTION
**Pull request by sdgamboa**
@mdozmorov, @Krithika-Bhuvan 

I updated the shortcodes for the site.

+ I removed days 2 and 3 data for a moment just to adapt my code. I'll upload them again later in the day.

+ I added instructions about how to fill the data in `data/abstracts`. This is in the README of the base directory.

+ The only short talks ready is "Short talks, Systems Biology/Epigenetics Track". I will improve the look of this page later.

+ Probably we could meet to clarify any remaining doubts or to discuss the format of the schedule?

### CODE REVIEW

**Comment by mdozmorov** [comment]
It looks intuitive, the "talks" field helps for short talks tracks. It doesn't seem to work for the moment (day 1 tracks bring empty pages). Let's meet and discuss other details - will message on Slack.

**Comment by sdgamboa** [comment]
The only short talks track ready is "Short talks, Systems Biology/Epigenetics Track". That page should bring the right pages in the deploy preview)

**Comment by mdozmorov** [comment]
Indeed, that track works.  One minor thing - to fix README, lines in this section are mixed:
```
12. talks - this field is only for the short talk tracks. this should list
13. time - the time in 24h format. Example: 1300 for 1 PM.
the number of the papers under this track. This should be a yaml array.
Example: ["paper10", "paper20"]
```

**Comment by Krithika-Bhuvan** [comment]
Thanks Samuel. I am updating the schedule data file based on your Readme
file.
https://docs.google.com/spreadsheets/d/1tGtGffcbCRxQFjE3ej42IcWlN4FJCsuQeZvETt9g0oA/edit#gid=0

The Rmd code I have will re-generate the yaml files for day2 and day3.

The individual details about the short talks will be manually created.

Thanks,
Krithika

**Pull request merged**
