### PR TITLE
create a partial for news

### PR DESCRIPTION
**Pull request by sdgamboa**
@mdozmorov @Krithika-Bhuvan 

I started to address these points in the TODO list:

+ Make partials for current news. Currently, they are added directly to `layouts/index.html` (README).
+ Modular news on the front page. Currently, they are edited directly in `index.html` (Google docs).

I started by creating the `layout/partials/news.html` file and moving in there the news contents from `themes/hugo-universal-theme/layouts/index.html`.

### CODE REVIEW

**Comment by mdozmorov** [comment]
It is cleaner, but the news are still hard-coded in the HTML code. Can we make news like blog posts, written in Markdown? It'll be easier to write news updates and allow for multiple news posts to be added (scrollable). It is not strictly necessary as we have just the due dates, but is it possible/straightforward to do?

**Comment by sdgamboa** [comment]
@mdozmorov, I think I get it now. The news should look like [this section](https://bcc2020.github.io/news/) in a separate menu?

**Comment by mdozmorov** [comment]
Exactly! Again, within reason, if it's too complex, we can just keep your `news.html` setup, which is already better.

**Comment by sdgamboa** [comment]
@mdozmorov, I added a menu for news in which the news items are displayed as a list of blog posts. New items can be added in the `content/news/` directory as separate markdown files. I had to add `hugo --buildFuture` to the netifly.toml file in order to view posts with future publication dates. I haven't removed the news section from the front page yet.

**Comment by mdozmorov** [comment]
The front page with `hews.html` partial looks good, let's keep it. The News menu and content are awesome. Do we need `layouts/_default/list.html`? I'm not sure how it plays with the modified `themes/hugo-universal-theme/layouts/_default/list.html`. We can catch up after the main meeting. @Krithika-Bhuvan, please, check. 

Minor: there's a typo in "regiter". Is this correct if you set `draft: true` in YAML header, the post won't display? We may want to hide the other posts.

**Comment by sdgamboa** [comment]
+ I moved the `layouts/_default/list.html` file to `layouts/news/list.html` so it should only affect the news posts. This file is not really necessary for displaying the list of posts; however, I made a couple of changes in the list.html file to display content (in case some text is needed on top of the list of news) and reverse the order (newest posts are shown on top).
+ I restored the original `themes/hugo-universal-theme/layouts/_default/list.html` from the master branch of the repo.
+ I also set to "draft" all future news posts.
+ I corrected the typo of "register."

**Comment by mdozmorov** [comment]
Looks great!

**Pull request merged**
