### PR TITLE
Schedule modular

### PR DESCRIPTION
**Pull request by sdgamboa**
@mdozmorov, I added some modularity to the schedule. Files for the abstracts (and events) must be added in two places:

1. `data/abstracts` (the main place that populates the schedule tables). All of the data is provided in these files.
2. `content/abstracts` (files used to create markdown files). Only three types of data must be provided for these files: title, tag (session_type), and paper number (e.g., paper1). The rest of info is populated from `data/abstracts`. I created an archetype to make it easier to create the paper files, e.g., `hugo new asbtracts/paper10.md` (this must be executed in the base directory of the hugo/github project).

The abstracts are provided as independent yaml files in `data/abstracts`. The abstracts are ordered automatically according to date and time. They have different colors according to type of session. Links to youtube and twitter are added when available.

If this format is OK, I'll start populating all of the tables.

#20

### CODE REVIEW

**Comment by mdozmorov** [comment]
Looks great! I've been thinking if it is possible to have just one YAML file per paper. It seems one file for populating the schedule and another for the abstract page is what we have to do.

**Comment by sdgamboa** [comment]
@mdozmorov, @Krithika-Bhuvan, I couldn't figure out a way to do that.

It seems that hugo doesn't support creating individual markdwon files from yaml files in the `data/abstracts/` folder. And I don't know how to access the data in the front matter of all markdown files in `data/abstracts/` and use them in the shortcode.

As an alternative solution, I can write a bash script to create the markdown files for the abstracts automatically from the yaml files in `data/abstracts/`. So only the `data/abstracts/*yaml` files must be created.

**Comment by mdozmorov** [comment]
A bash script will be helpful. I'll get to making yaml files tonight.

**Comment by sdgamboa** [comment]
I created the bash script. It could be executed once all of the yaml files have been created in `data/abstracts`. 


Usage (in the base directory of the repo)

```
chmod +x create_abstracts.sh # it should have executing permissions already
bash create_abstracts.sh
```

**Comment by mdozmorov** [comment]
Great. We have day 1. I changed file names for clarity. Not sure what to do with "Short talks" - they have multiple abstracts. Let's see if Krithika can help.

**Comment by Krithika-Bhuvan** [comment]
Thanks Sam and Mikhail. I will take a look on Monday.
From what I understand the only Solution is to put all the information on
one yaml file - is that correct?

**Comment by mdozmorov** [comment]
One yaml file per schedule entry, e.g., one workshop - one file. It should be straightforward when you pull and see day 1 files. Thanks, Krithika, Samuel!

**Pull request merged**
